---
- name:  Configure Backend for Expense App
  hosts: all
  become: yes
  tasks:

  - name: Disable Default NodeJs version module
    shell: dnf module disable nodejs -y

  - name: Enable Default NodeJs version module
    shell: dnf module disable nodejs:20 -y

  - name: Install NodeJs
    dnf:
      name: nodejs
      state: installed

  - name: Add application user
    user:
      name: expense

  - name: Copy Backend service
    copy:
      src: backend.service
      dest: /etc/systemd/system/backend.service

  - name: Clean old content
    file:
      path: /app
      state: absent

  - name: Create App directory
    file:
      path: /app
      state: directory

  - name: Download App content
    get_url:
      url: https://expense-artifacts.s3.amazonaws.com/expense-backend-v2.zip
      dest: /tmp/backend.zip

  - name: Extract backend zip content
    unarchive:
      src: /tmp/backend.zip
      dest: /app
      remote_src: yes

  - name: Download NodeJs dependencies.
    community.general.npm:
      name: nodejs
      path: /app

  - name: Install required Python package for MySQL (PyMySQL)
    pip:
      name: PyMySQL
      state: present

  - name: Install MySQL Client
    dnf:
      name: mysql
      state: installed


  - name: Load Schema
    community.mysql.mysql_db:
      state: import
      name: all
      target: /app/schema/backend.sql
      login_user: root
      login_password: ExpenseApp@1
      login_host: mysql-dev.awsdevops.sbs

  - name: Start Backend service
    service:
      name: backend
      state: restarted
      enable: yes
      daemon-reloaded: yes


