---
- name: Install and Configure Nginx for Expense App
  hosts: all
  become: yes
  tasks:

    - name: Install Nginx
      ansible.builtin.dnf:
        name: nginx
        state: latest

    - name: Copy Expense Nginx Conf
      ansible.builtin.copy:
        src: expense.conf
        dest: /etc/nginx/default.d/expense.conf

    - name: Clean old content
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: absent

    - name: Create App directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: directory

    - name: Download App content
      ansible.builtin.get_url:
        url: https://expense-artifacts.s3.amazonaws.com/expense-frontend-v2.zip
        dest: /tmp/frontend.zip

    - name: Extract frontend zip content
      ansible.builtin.unarchive:
        src: /tmp/frontend.zip
        dest: /usr/share/nginx/html
        remote_src: yes

    - name: Print Task Heading - Start Nginx Service
      ansible.builtin.debug:
        msg: "Starting and Enabling Nginx Service"

    - name: Start Nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
