  - name: Install MySQL server
    dnf:
      name: mysql-server
      state: installed

  - name: Enable and Start MySQL server
    service:
      name: mysqld
      state: started
      enabled: yes

  - name: Setup MySql password
    shell: mysql_secure_installation --set-root-pass ExpenseApp@1
# tasks file for mysql
